services:
  markdown_viewer:
    platform: "linux/amd64"
    build:
      context: .
    restart: "no"
    environment:
      TITLE: "Markdown Viewer"
    volumes:
      - ./public/favicon.svg:/app/public/favicon.svg
      - ./src/content/md/:/app/src/content/md:ro
    ports:
      - "8080:80"
